docker:
  image: yegor256/rultor-image:1.21.0
merge:
  script: |-
    sudo docker build "$(pwd)"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/^0.0.0/${tag}/" Dockerfile
    sudo docker build "$(pwd)"
